### Find All Contents
GET http://localhost:8080/api/content

### Get Content By Id
GET http://localhost:8080/api/content

### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "My Second Post",
  "desc": "my second post",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2024-02-18T17:15:25.2044481",
  "dateUpdate": null,
  "url": ""
}

### Update Existing Content If exists
PUT http://localhost:8080/api/content/2
Content-Type: application/json

{
  "id": 2,
  "title": "My second Blog Post",
  "desc": "my second blog post",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2024-02-18T17:15:25.2044481",
  "dateUpdate": "2024-02-18T17:15:25.2044481",
  "url": "http://localhost:8080/his-mom-blog-post"
}
### Delete by id
DELETE http://localhost:8080/api/content/2


